from pyspark import Row
from pyspark.sql import DataFrame
from pyspark.sql.types import ArrayType, StringType
from pydantic import BaseModel

from data_refiner.core import recorder
from data_refiner.core.meta_operator import Reducer, OperatorConstraint, processing_operator
from data_refiner.ops.common.tools import resonance
from data_refiner.utils.tools import check_column_schema


@processing_operator
class ArrayFlatmapCountReducer(Reducer, OperatorConstraint):
    """
    Count the number of elements in an array field, it will flatten the array and count the number of elements. 计算数组字段中的元素数量，它会将数组展平并计算元素数量
    """

    CONSTRAINT = """
### Input Column Constraints 输入列约束
* `field` -> Target Source Column 目标源列: The input DataFrame must contain this specified array column. 输入 DataFrame 必须包含此指定的数组列。
  * Data Type 数据类型: `ArrayType(StringType())` 数组字符串类型. This column must consist of arrays containing string elements to undergo flattening and frequency aggregation. 该列必须由包含字符串元素的数组组成，以便进行展平与频次聚合。

### Argument and Column Mapping 参数与列的映射
* `field` -> Source Array and Result Key Column 源数组与结果键列: This parameter acts as both the input identifier for the array to be exploded and the final output column name for the distinct unnested string tokens. 该参数既作为要被炸裂的数组的输入标识符，又作为最终输出列中去重后展开字符串词项的列名。
* `"count"` -> Built-in Metrics Column 内置指标列: A hardcoded output column name generated by the aggregation logic to hold the frequency calculation. 由聚合逻辑生成的硬编码输出列名，用于存放频次计算结果。

### Schema Transformation Process Schema 转换过程
* Phase 1: Selective Projection and Verification 阶段 1：选择性投影与校验
  * The operator invokes `.select()` to actively prune all columns from the input DataFrame except for the specific column defined by `field`, reducing the schema width to a single column. 算子调用 `.select()` 主动裁剪掉输入 DataFrame 中除 `field` 指定的特定列之外的所有列，将 schema 宽度缩减为单列。
* Phase 2: RDD Flattening and Key-Value Aggregation 阶段 2：RDD 展平与键值对聚合
  * The DataFrame is converted to a low-level RDD where a `.flatMap()` operation unnests the arrays, turning rows of arrays into individual string element streams. DataFrame 被转换为低级 RDD，通过 `.flatMap()` 操作展开数组，将每行的数组转化为独立的字符串元素流。
  * A `.map()` operator transforms each string element into a coordinate pair `(x, 1)`, which is subsequently compiled via `.reduceByKey()` to calculate the aggregate summation of occurrences. 一个 `.map()` 算子将每个字符串元素转换为坐标对 `(x, 1)`，随后通过 `.reduceByKey()` 进行编译以计算出现次数的累加和。
* Phase 3: Row Restructuring and Structural Inference 阶段 3：行重构与结构推断
  * A final RDD map operation wraps the key-value outcomes inside Spark `Row` objects, assigning the original string to the key named by `field` and the sum to the key `"count"`. 最后的 RDD map 操作将键值对结果包装在 Spark `Row` 对象中，将原始字符串分配给由 `field` 命名的键，将总和分配给键 `"count"`。
  * The `.toDF()` method is evaluated to implicitly infer and construct a clean two-column DataFrame schema from the structured rows. 调用 `.toDF()` 方法，基于结构化行隐式推断并构建一个干净的双列 DataFrame schema。

### Output Schema Final State 输出 Schema 最终态
* `field` -> Flattened Unique Term Column 展平后的唯一词项列: The first output column containing the unnested distinct elements. 第一个输出列，包含展开后的去重元素。
  * Data Type 数据类型: `StringType()` 字符串类型. This column holds the individual string elements extracted and flattened from the source arrays. 该列存放从源数组中提取并展平的单个字符串元素。
* `count` -> Aggregated Frequency Column 聚合频次列: The second output column containing the total occurrence metric. 第二个输出列，包含总出现次数指标。
  * Data Type 数据类型: `LongType()` 长整型. This column represents the computed total count of each unique string element across all arrays in the dataset. 该列代表数据集中所有数组中每个唯一字符串元素的计算总数。"""

    def count_by(self, df: DataFrame):
        return (
            df.rdd.flatMap(lambda x: x[self.field])
            .map(lambda x: (x, 1))
            .reduceByKey(lambda x, y: x + y)
            .map(lambda x: Row(**{self.field: x[0], "count": x[1]}))
            .toDF()
        )

    @resonance
    def process(self, *args, **kwargs) -> DataFrame:
        df = recorder.load(self.input_df).select(self.field)
        check_column_schema(df, self.field, ArrayType(StringType()))
        res_df = self.count_by(df)
        recorder.record(self.output_df, res_df)
        return res_df
