from pyspark import Row
from pyspark.sql import DataFrame
from pyspark.sql.types import StringType
from pydantic import BaseModel

from data_refiner.core import recorder
from data_refiner.core.meta_operator import Reducer, OperatorConstraint, processing_operator
from data_refiner.ops.common.tools import resonance
from data_refiner.utils.tools import check_column_schema


@processing_operator
class FieldCountReducer(Reducer, OperatorConstraint):
    """
    Count the number of occurrences of a specific field in a DataFrame. 统计 DataFrame 中特定字段出现的次数
    """

    CONSTRAINT = """
### Input Column Constraints 输入列约束
* `field` -> Target Source Column 目标源列: The input DataFrame must contain this specified categorical or text column. 输入 DataFrame 必须包含此指定的分类或文本列。
  * Data Type 数据类型: `StringType()` 字符串类型. This column must contain string data whose unique value occurrences will be aggregated and counted. 该列必须包含字符串数据，其唯一值的出现次数将被聚合和计数。

### Argument and Column Mapping 参数与列的映射
* `field` -> Source Key and Result Value Column 源键与结果值列: This parameter defines the name of the input column to be aggregated, which also serves as the final column name for the distinct string keys in the output DataFrame. 该参数指定要进行聚合的输入列名称，它同时也作为输出 DataFrame 中去重后字符串键的最终列名。
* `"count"` -> Aggregated Metric Column 聚合指标列: A hardcoded output column name automatically generated by the reduction process to store the summation of occurrences. 一个由规约过程自动生成的硬编码输出列名，用于存储出现次数的累加和。

### Schema Transformation Process Schema 转换过程
* Phase 1: RDD Extraction and Pair Mapping 阶段 1：RDD 提取与对映射
  * The verified DataFrame is converted into a low-level RDD, and a `.map()` operation is applied to extract the target column value specified by `field`. 校验后的 DataFrame 被转换为低级 RDD，并应用 `.map()` 操作来提取由 `field` 指定的目标列值。
  * Each record is structured into a primitive key-value tuple format `(x[field], 1)`, stripping away all other accompanying input columns from the active processing context. 每个记录被结构化为原始的键值对元组格式 `(x[field], 1)`，从而将所有其他伴随的输入列从当前处理上下文中剥离。
* Phase 2: Reduction and Row Reconstruction 阶段 2：规约与行重构
  * The `.reduceByKey()` operator aggregates the tuple stream, combining identical string keys and summing their integer indicators to calculate global frequencies. `.reduceByKey()` 算子对元组流进行聚合，合并相同的字符串键并对其整型指示器求和以计算全局频次。
  * A secondary `.map()` operator transforms the aggregated pairs back into Spark `Row` objects, explicitly mapping the unique string to the dynamic key defined by `field` and the computed sum to the key `"count"`. 第二个 `.map()` 算子将聚合后的键值对重新转换为 Spark `Row` 对象，显式地将唯一字符串映射到由 `field` 定义的动态键，并将计算出的总和映射到键 `"count"`。
* Phase 3: Structural Inference 阶段 3：结构推断
  * The final RDD invokes `.toDF()`, triggering the Spark engine to inspect the reconstructed rows and infer a fresh, optimized two-column DataFrame schema. 最后的 RDD 调用 `.toDF()`，触发 Spark 引擎检查重构后的行并推断出一个全新的、优化后的双列 DataFrame schema。

### Output Schema Final State 输出 Schema 最终态
* `field` -> Unique Value Column 唯一值列: The first output column containing the distinct categorical keys. 第一个输出列，包含去重后的分类键。
  * Data Type 数据类型: `StringType()` 字符串类型. This column holds the unique, un-duplicated string values extracted from the source dataset. 该列存放从源数据集中提取的唯一、去重后的字符串值。
* `count` -> Frequency Summation Column 频次累加列: The second output column containing the calculation metrics. 第二个输出列，包含计算指标。
  * Data Type 数据类型: `LongType()` 长整型. This column represents the final computed total frequency of each distinct string token across the entire input dataset. 该列代表每个不同字符串标记在整个输入数据集中的最终计算总频次。"""

    def count_by(self, df: DataFrame):
        return (
            df.rdd.map(lambda x: (x[self.field], 1))
            .reduceByKey(lambda x, y: x + y)
            .map(lambda x: Row(**{self.field: x[0], "count": x[1]}))
            .toDF()
        )

    @resonance
    def process(self, *args, **kwargs) -> DataFrame:
        df = recorder.load(self.input_df)
        check_column_schema(df, self.field, StringType())
        res_df = self.count_by(df)
        recorder.record(self.output_df, res_df)
        return res_df
