from data_refiner.core import recorder
from pyspark.sql import SparkSession
from data_refiner.ops.filter.null_rows_filter import NullRowsFilter


class TestDropNullRowsFilter:
    def test_drop_null_rows_all_columns(self, spark: SparkSession):
        test_data = [
            (
                "U001",
                "Li Hua",
                "22",
                "M",
                "杭州",
                "浙江",
                "河南",
                "Bachelor",
                "85000",
                "Engineer",
                "2023-02-12",
                "2025-01-08",
                "13800001111",
                "lihua@example.com",
                "Huawei",
                "5.2.1",
                "3200",
                "news",
                "88",
                "92",
            ),
            (
                "U002",
                "Wang Lei",
                "29",
                "F",
                "杭州",
                "浙江",
                "河南",
                "Master",
                "120000",
                "Designer",
                "2022-11-03",
                "2025-01-06",
                "13900002222",
                None,
                "Apple",
                "5.2.1",
                "5800",
                "finance",
                "76",
                "85",
            ),
            (
                "U003",
                "Zhang Ming",
                "19",
                "M",
                "上海",
                "上海",
                "安徽",
                "HighSchool",
                "45000",
                "Student",
                "2024-01-18",
                "2025-01-09",
                "13700003333",
                "zhangming@example.com",
                "Xiaomi",
                "5.1.0",
                "900",
                "games",
                "90",
                "78",
            ),
        ]
        schema = [
            "user_id",
            "name",
            "age",
            "gender",
            "city",
            "province",
            "hometown",
            "education",
            "income",
            "profession",
            "register_time",
            "last_login",
            "phone",
            "email",
            "device_brand",
            "app_version",
            "annual_cost",
            "category_fav",
            "score_math",
            "score_english",
        ]
        df = spark.createDataFrame(test_data, schema)
        recorder.record("test.df", df)

        op = NullRowsFilter(
            input_df="test.df", output_df="test.df_output", field="email", show=True
        )
        result_df = op.process(spark=spark)

        # Only U001 and U003 should remain (U002 has null email)
        expected_data = [
            (
                "U001",
                "Li Hua",
                "22",
                "M",
                "杭州",
                "浙江",
                "河南",
                "Bachelor",
                "85000",
                "Engineer",
                "2023-02-12",
                "2025-01-08",
                "13800001111",
                "lihua@example.com",
                "Huawei",
                "5.2.1",
                "3200",
                "news",
                "88",
                "92",
            ),
            (
                "U003",
                "Zhang Ming",
                "19",
                "M",
                "上海",
                "上海",
                "安徽",
                "HighSchool",
                "45000",
                "Student",
                "2024-01-18",
                "2025-01-09",
                "13700003333",
                "zhangming@example.com",
                "Xiaomi",
                "5.1.0",
                "900",
                "games",
                "90",
                "78",
            ),
        ]
        expected_df = spark.createDataFrame(expected_data, schema)
        assert result_df.collect() == expected_df.collect()

    def test_drop_null_rows_specific_columns(self, spark: SparkSession):
        test_data = [
            (
                "U001",
                "Li Hua",
                "22",
                "M",
                "杭州",
                "浙江",
                "河南",
                "Bachelor",
                "85000",
                "Engineer",
                "2023-02-12",
                "2025-01-08",
                "13800001111",
                "lihua@example.com",
                "Huawei",
                "5.2.1",
                "3200",
                "news",
                "88",
                "92",
            ),
            (
                "U002",
                "Wang Lei",
                None,
                "F",
                "杭州",
                "浙江",
                "河南",
                "Master",
                "120000",
                "Designer",
                "2022-11-03",
                "2025-01-06",
                "13900002222",
                "wanglei@example.com",
                "Apple",
                "5.2.1",
                "5800",
                "finance",
                None,
                "85",
            ),
            (
                "U003",
                "Zhang Ming",
                "19",
                "M",
                "上海",
                "上海",
                "安徽",
                "HighSchool",
                "45000",
                "Student",
                "2024-01-18",
                "2025-01-09",
                "13700003333",
                "zhangming@example.com",
                "Xiaomi",
                "5.1.0",
                "900",
                "games",
                "90",
                "78",
            ),
        ]
        schema = [
            "user_id",
            "name",
            "age",
            "gender",
            "city",
            "province",
            "hometown",
            "education",
            "income",
            "profession",
            "register_time",
            "last_login",
            "phone",
            "email",
            "device_brand",
            "app_version",
            "annual_cost",
            "category_fav",
            "score_math",
            "score_english",
        ]
        df = spark.createDataFrame(test_data, schema)
        recorder.record("test.df", df)

        op = NullRowsFilter(
            input_df="test.df",
            output_df="test.df_output",
            field="email",
            columns_to_check=["age", "score_math"],
            show=True,
        )
        result_df = op.process(spark=spark)

        # Only U001 and U003 should remain (U002 has null in age and score_math)
        expected_data = [
            (
                "U001",
                "Li Hua",
                "22",
                "M",
                "杭州",
                "浙江",
                "河南",
                "Bachelor",
                "85000",
                "Engineer",
                "2023-02-12",
                "2025-01-08",
                "13800001111",
                "lihua@example.com",
                "Huawei",
                "5.2.1",
                "3200",
                "news",
                "88",
                "92",
            ),
            (
                "U003",
                "Zhang Ming",
                "19",
                "M",
                "上海",
                "上海",
                "安徽",
                "HighSchool",
                "45000",
                "Student",
                "2024-01-18",
                "2025-01-09",
                "13700003333",
                "zhangming@example.com",
                "Xiaomi",
                "5.1.0",
                "900",
                "games",
                "90",
                "78",
            ),
        ]
        expected_df = spark.createDataFrame(expected_data, schema)
        assert result_df.collect() == expected_df.collect()
