from pyspark.sql import DataFrame
from pyspark.sql.types import StructType, StructField, StringType
from pydantic import BaseModel

from data_refiner.core.meta_operator import PathReader, processing_operator
from data_refiner.ops.common.tools import resonance


@processing_operator
class WholeTextFileReader(PathReader):
    """
    Reads the whole text file as a string. Useful for reading large text files like .logs, .html files, etc. 将整个文本文件读取为字符串。适用于读取大型文本文件，例如 .log 文件、.html 文件等
    """

    CONSTRAINT = """
### Input Column Constraints 输入列约束
* `input_path` -> Target External Storage 目标外部存储: The directory or file path residing on the file system serves as the raw input to the reader engine. 位于文件系统上的目录或文件路径充当读取器引擎的原始输入。
  * Data Type 数据类型: `Any` 任意类型. The target source points to physical files (e.g., `.logs`, `.html`, `.txt`) stored on disk rather than an existing structural dataset. 目标源指向存储在磁盘上的物理文件（例如 `.logs`, `.html`, `.txt`），而不是现有的结构化数据集。

### Argument and Column Mapping 参数与列的映射
* `input_path` -> Ingestion Directory String 导入目录字符串: This parameter defines the file URI or directory path passed down to the underlying Spark core execution context. 该参数定义了传递给底层 Spark 核心执行上下文的文件 URI 或目录路径。
  * No individual configuration arguments are mapped to specific inline columns; instead, the entire structural mapping of the output DataFrame is statically preset by the operator logic. 没有单独的配置参数映射到特定的行内列；相反，输出 DataFrame 的整个结构映射由算子逻辑静态预设。

### Schema Transformation Process Schema 转换过程
* Phase 1: Low-Level Pair RDD Generation 阶段 1：低级键值对 RDD 生成
  * The Spark context invokes the `spark.sparkContext.wholeTextFiles()` method using the directory specified by `input_path`. Spark 上下文使用 `input_path` 指定的目录调用 `spark.sparkContext.wholeTextFiles()` 方法。
  * This initializes a specialized low-level Pair RDD where each individual file is treated as a single undivided record. The key represents the absolute file path, and the value represents the entire text payload of that file. 这将初始化一个特化的低级键值对 RDD，其中每个单独的文件都被视为一条未分割的记录。键代表绝对文件路径，值代表该文件的整个文本净荷。
* Phase 2: Schema Enforcement and DataFrame Creation 阶段 2：Schema 强制结合与 DataFrame 创建
  * A fixed metadata structure `schema` is explicitly instantiated via `StructType`, containing exactly two `StringType()` fields named `"file_path"` and `"text"`. 一个固定的结构化元数据 `schema` 通过 `StructType` 被显式实例化，包含且仅包含两个名为 `"file_path"` 和 `"text"` 的 `StringType()` 字段。
  * The operator invokes `spark.createDataFrame(rdd, schema)` to bind the compiled structure directly onto the low-level Pair RDD, generating a strongly-typed structured dataset. 算子调用 `spark.createDataFrame(rdd, schema)` 将编译好的结构直接绑定到低级键值对 RDD 上，从而生成一个强类型的结构化数据集。

### Output Schema Final State 输出 Schema 最终态
* `file_path` -> Absolute Source Path Column 绝对源路径列: The first output field holding the location identifier. 第一个输出列，存放位置标识符。
  * Data Type 数据类型: `StringType()` 字符串类型. This column stores the absolute file URI string generated by the file system reader for each file processed. 该列存储由文件系统读取器为每个已处理文件生成的绝对文件 URI 字符串。
* `text` -> Entire File Content Column 完整文件内容列: The second output field holding the full text string. 第二个输出列，存放完整的文本字符串。
  * Data Type 数据类型: `StringType()` 字符串类型. This column contains the entire raw text block loaded from the corresponding file, read completely as a single continuous string payload. 该列包含从对应文件中加载的整个原始文本块，完全作为一个连续的单一字符串净荷读取。"""

    @resonance
    def process(self, *args, **kwargs) -> DataFrame:
        spark = kwargs.get("spark")
        rdd = spark.sparkContext.wholeTextFiles(self.input_path)
        schema = StructType(
            [
                StructField("file_path", StringType(), True),
                StructField("text", StringType(), True),
            ]
        )
        return spark.createDataFrame(rdd, schema)
